# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: msg_broadcast_struct.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1amsg_broadcast_struct.proto\"\x86\x01\n\nSenderInfo\x12\x11\n\tip_origin\x18\x01 \x01(\t\x12\x11\n\tip_sender\x18\x02 \x01(\t\x12\x0e\n\x06msg_id\x18\x03 \x01(\x11\x12\x10\n\x08msg_type\x18\x04 \x01(\x11\x12\x12\n\nreputation\x18\x05 \x01(\x11\x12\x0f\n\x07\x62\x61ttery\x18\x06 \x01(\x11\x12\x0b\n\x03GPS\x18\x07 \x01(\x11\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'msg_broadcast_struct_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_SENDERINFO']._serialized_start=31
  _globals['_SENDERINFO']._serialized_end=165
# @@protoc_insertion_point(module_scope)
